#! /usr/bin/env ruby
# This console script adapted from:rake
#   http://barkingiguana.com/blog/2009/01/25/scriptconsole-for-your-application/

ENV["RACK_ENV"] = ARGV[0] || "development"

libs = []
libs << "irb/completion"
libs << File.join(File.dirname(__FILE__),*%w{.. config boot})


command_line = []
command_line << "irb"
command_line << libs.inject("") { |acc, lib| acc + %( -r "#{lib}") }
command_line << "--simple-prompt"
command = command_line.join(" ")

puts "Relax, the Console has taken the stage"
exec command
